<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.3" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.3" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.3" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.3" />
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.3" Condition="'$(Configuration)' == 'Debug'" />
    <PackageReference Include="Npgsql" Version="8.0.5" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Models\PlateauModele.cs" />
    <Compile Include="Models\BazookaModele.cs" />
    <Compile Include="Models\TourModele.cs" />
    <Compile Include="Models\DatabaseService.cs" />
    <Compile Include="Views\MainWindow.axaml.cs" />
    <Compile Include="Views\Plateaux.axaml.cs" />
    <Compile Include="App.axaml.cs" />
    <Compile Include="Program.cs" />
  </ItemGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

</Project>
