CREATE TABLE Usr (
    ID NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    prenom VARCHAR2(100),
    mdp VARCHAR2(50),
    id_poste VARCHAR2(100)
);


--CREE UNE SEQUENCE == (auto-increment)

-- SEQ USER
CREATE SEQUENCE seq_usr
START WITH 1
INCREMENT BY 1;

--TIGGER USER
CREATE OR REPLACE TRIGGER trg_usr_id
BEFORE INSERT ON Usr
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := seq_usr.NEXTVAL;
    END IF;
END;
/


ALTER TABLE MED_ORDONNANCE_FILLE
ADD (MY_USER NUMBER);


--Sq DEDECINE MATRICULE
CREATE SEQUENCE seq_medecin
START WITH 4
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER trg_medecin_id
BEFORE INSERT ON MED_MEDECIN
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'DR' || LPAD(seq_medecin.NEXTVAL, 5, '0');
        :NEW.MATRICULE := :NEW.ID;
    END IF;
END;
/

ALTER TABLE MED_MEDECIN
ADD (MY_USER NUMBER);


--SEQUENCE MED_ORDONNANCE FILE

CREATE SEQUENCE seq_ORD_FILLE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_ord_f
BEFORE INSERT ON MED_ORDONNANCE_FILLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ORDF' || LPAD(seq_ORD_FILLE.NEXTVAL, 5, '0');
    END IF;
END;
/

-----SEQ ORDONNANCE
CREATE SEQUENCE seqq_med_ordonnance
    START WITH 400
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER trg_med_ord_auto_id
BEFORE INSERT ON MED_ORDONNANCE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ORD' || LPAD(seqq_med_ordonnance.NEXTVAL, 6, '0');
    END IF;
END;
/


--- SEQ INVENTAIRE
CREATE OR REPLACE SEQUENCE seq_Inventaire
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_inv
BEFORE INSERT ON INVENTAIRE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'IVT' || LPAD(seq_Inventaire.NEXTVAL, 5, '0');
    END IF;
END;
/


---INVENTAIREFILLE
CREATE OR REPLACE SEQUENCE seq_InventaireFille
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_invF
BEFORE INSERT ON INVENTAIREFILLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'IVTFI' || LPAD(seq_InventaireFille.NEXTVAL, 5, '0');
    END IF;
END;
/


--CLIENT
CREATE SEQUENCE seq_client
START WITH 458
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE FUNCTION seq_client_nextVal
RETURN NUMBER
AS
    v_next NUMBER;
BEGIN
    SELECT seq_client.NEXTVAL INTO v_next FROM dual;
    RETURN v_next;
END;
/


---SOCIETE
CREATE SEQUENCE seq_societe
START WITH 26
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER trg_soc
BEFORE INSERT ON SOCIETECONDITION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'SOCC' || LPAD(seq_societe.NEXTVAL, 5, '0');
    END IF;
END;
/


--ETATSTOK
CREATE SEQUENCE SEQ_ETATSTOCK
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_ETATSTOCK_ID
BEFORE INSERT ON ETATSTOCK
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ETSTK' || LPAD(SEQ_ETATSTOCK.NEXTVAL, 6, '0');
    END IF;
END;
/

--MVTSTOCK
CREATE SEQUENCE SEQ_MVTSTOCK
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRGG_MVTSTOCK_ID
BEFORE INSERT ON MVTSTOCK
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'MVTSTT' || LPAD(SEQ_MVTSTOCK.NEXTVAL, 6, '0');
    END IF;
END;
/


---MVTSFI
CREATE SEQUENCE SEQ_MVTSTOCKFILLE
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_MVTSFILLE_ID
BEFORE INSERT ON MVTSTOCKFILLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'MVTSFI' || LPAD(SEQ_MVTSTOCKFILLE.NEXTVAL, 6, '0');
    END IF;
END;
/


ALTER TABLE ETATSTOCK 
ADD IDMEDICAMENT VARCHAR2(50);

ALTER TABLE ETATSTOCK
ADD CONSTRAINT ETATSTOCK_MEDICAMENT_FK
FOREIGN KEY (IDMEDICAMENT)
REFERENCES AS_INGREDIENTS(ID);
