-- Script to migrate salary_history PK and allow empno NULL with ON DELETE SET NULL
-- WARNING: This is invasive. BACKUP your schema before running (export or dump).
-- Run as schema owner (SCOTT) or DBA in SQL*Plus / SQL Developer.

SET SERVEROUTPUT ON SIZE 100000
PROMPT === 1) Diagnostic: check referencing constraints ===
SELECT owner, constraint_name, constraint_type
FROM all_constraints
WHERE table_name = 'SALARY_HISTORY';

PROMPT === 2) Ensure no other table has FK referencing current PK (review output) ===
SELECT a.owner, a.constraint_name, a.table_name, a.column_name, c_pk.table_name referenced_table
FROM all_cons_columns a
JOIN all_constraints c ON a.owner = c.owner AND a.constraint_name = c.constraint_name
LEFT JOIN all_constraints c_pk ON c.r_constraint_name = c_pk.constraint_name
WHERE c.table_name = 'SALARY_HISTORY';

PROMPT === 3) Add surrogate primary key column 'id' (IDENTITY) ===
ALTER TABLE salary_history ADD (id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY);

PROMPT === 4) Populate id for existing rows if DB doesn't auto-populate existing rows (IDENTITY usually auto-fills for future inserts). If id is NULL for existing rows, fill using a sequence (uncomment if needed):
-- CREATE SEQUENCE salary_history_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
-- UPDATE salary_history SET id = salary_history_seq.NEXTVAL WHERE id IS NULL;
-- COMMIT;

PROMPT === 5) Drop existing PK (PK_SALARY_HISTORY) - ensure you have its exact name from diagnostic
ALTER TABLE salary_history DROP CONSTRAINT PK_SALARY_HISTORY;

PROMPT === 6) Add new PK on id
ALTER TABLE salary_history ADD CONSTRAINT PK_SALARY_HISTORY_ID PRIMARY KEY (id);

PROMPT === 7) Make empno nullable
ALTER TABLE salary_history MODIFY (empno NULL);

PROMPT === 8) Drop FK to EMP if exists and recreate with ON DELETE SET NULL
-- Replace FK name if different
BEGIN
  FOR r IN (
    SELECT uc.constraint_name
    FROM user_constraints uc
    LEFT JOIN user_constraints pk ON uc.r_constraint_name = pk.constraint_name
    WHERE uc.table_name = 'SALARY_HISTORY' AND uc.constraint_type = 'R' AND pk.table_name = 'EMP'
  ) LOOP
    BEGIN
      EXECUTE IMMEDIATE 'ALTER TABLE salary_history DROP CONSTRAINT ' || r.constraint_name;
      DBMS_OUTPUT.PUT_LINE('Dropped constraint ' || r.constraint_name);
    EXCEPTION WHEN OTHERS THEN
      DBMS_OUTPUT.PUT_LINE('Could not drop constraint ' || r.constraint_name || ': ' || SQLERRM);
    END;
  END LOOP;
END;
/

ALTER TABLE salary_history
  ADD CONSTRAINT FK_SALARY_HISTORY_EMP FOREIGN KEY (empno)
  REFERENCES emp(empno)
  ON DELETE SET NULL;

PROMPT === 9) Verify final constraints and columns
SELECT constraint_name, constraint_type FROM user_constraints WHERE table_name = 'SALARY_HISTORY';
SELECT column_name, data_type, nullable FROM user_tab_columns WHERE table_name = 'SALARY_HISTORY' ORDER BY column_id;

PROMPT === Done. Test by deleting an emp and checking salary_history.empno becomes NULL.
