-- SQL script to create overtime_entries table
-- Run as schema owner (e.g., SCOTT)

CREATE TABLE overtime_entries (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  employee_id NUMBER NOT NULL,
  period_start DATE NOT NULL,
  period_type VARCHAR2(20) NOT NULL,
  year NUMBER(4) NOT NULL,
  month NUMBER(2) NULL,
  hours NUMBER(10,2) NOT NULL,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Index on employee/year/month for queries
CREATE INDEX idx_overtime_emp_ym ON overtime_entries(employee_id, year, month);
