CREATE TABLE Usr (
    ID NUMBER PRIMARY KEY,
    name VARCHAR2(100),
    prenom VARCHAR2(100),
    mdp VARCHAR2(50),
    id_poste VARCHAR2(100)
);

--CREE UNE SEQUENCE == (auto-increment)

-- SEQ USER
CREATE SEQUENCE seq_usr
START WITH 1
INCREMENT BY 1;

--TIGGER USER
CREATE OR REPLACE TRIGGER trg_usr_id
BEFORE INSERT ON Usr
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := seq_usr.NEXTVAL;
    END IF;
END;
/


ALTER TABLE MED_ORDONNANCE_FILLE
ADD (MY_USER NUMBER);


--Sq DEDECINE MATRICULE
CREATE SEQUENCE seq_medecin
START WITH 4
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER trg_medecin_id
BEFORE INSERT ON MED_MEDECIN
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'DR' || LPAD(seq_medecin.NEXTVAL, 5, '0');
        :NEW.MATRICULE := :NEW.ID;
    END IF;
END;
/

ALTER TABLE MED_MEDECIN
ADD (MY_USER NUMBER);


--SEQUENCE MED_ORDONNANCE FILE

CREATE SEQUENCE seq_ORD_FILLE
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_ord_f
BEFORE INSERT ON MED_ORDONNANCE_FILLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ORDF' || LPAD(seq_ORD_FILLE.NEXTVAL, 5, '0');
    END IF;
END;
/

-----SEQ ORDONNANCE
CREATE SEQUENCE seqq_med_ordonnance
    START WITH 400
    INCREMENT BY 1
    NOCACHE;

CREATE OR REPLACE TRIGGER trg_med_ord_auto_id
BEFORE INSERT ON MED_ORDONNANCE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ORD' || LPAD(seqq_med_ordonnance.NEXTVAL, 6, '0');
    END IF;
END;
/


--- SEQ INVENTAIRE
CREATE OR REPLACE SEQUENCE seq_Inventaire
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_inv
BEFORE INSERT ON INVENTAIRE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'IVT' || LPAD(seq_Inventaire.NEXTVAL, 5, '0');
    END IF;
END;
/


---INVENTAIREFILLE
CREATE OR REPLACE SEQUENCE seq_InventaireFille
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER trg_invF
BEFORE INSERT ON INVENTAIREFILLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'IVTFI' || LPAD(seq_InventaireFille.NEXTVAL, 5, '0');
    END IF;
END;
/


--CLIENT
CREATE SEQUENCE seq_client
START WITH 458
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE FUNCTION seq_client_nextVal
RETURN NUMBER
AS
    v_next NUMBER;
BEGIN
    SELECT seq_client.NEXTVAL INTO v_next FROM dual;
    RETURN v_next;
END;
/


---SOCIETE
CREATE SEQUENCE seq_societe
START WITH 26
INCREMENT BY 1
NOCACHE
NOCYCLE;


CREATE OR REPLACE TRIGGER trg_soc
BEFORE INSERT ON SOCIETECONDITION
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'SOCC' || LPAD(seq_societe.NEXTVAL, 5, '0');
    END IF;
END;
/


--ETATSTOK
CREATE SEQUENCE SEQ_ETATSTOCK
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_ETATSTOCK_ID
BEFORE INSERT ON ETATSTOCK
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ETSTK' || LPAD(SEQ_ETATSTOCK.NEXTVAL, 6, '0');
    END IF;
END;
/

--MVTSTOCK
CREATE SEQUENCE SEQ_MVTSTOCK
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRGG_MVTSTOCK_ID
BEFORE INSERT ON MVTSTOCK
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'MVTSTT' || LPAD(SEQ_MVTSTOCK.NEXTVAL, 6, '0');
    END IF;
END;
/


---MVTSFI
CREATE SEQUENCE SEQ_MVTSTOCKFILLE
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE OR REPLACE TRIGGER TRG_MVTSFILLE_ID
BEFORE INSERT ON MVTSTOCKFILLE
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'MVTSFI' || LPAD(SEQ_MVTSTOCKFILLE.NEXTVAL, 6, '0');
    END IF;
END;
/


ALTER TABLE ETATSTOCK 
ADD IDMEDICAMENT VARCHAR2(50);

ALTER TABLE ETATSTOCK
ADD CONSTRAINT ETATSTOCK_MEDICAMENT_FK
FOREIGN KEY (IDMEDICAMENT)
REFERENCES AS_INGREDIENTS(ID);



----- IDUNITE dans AS_INGREDIENTS
ALTER TABLE VANIALA.AS_INGREDIENTS
ADD IDUNITE VARCHAR2(255);

ALTER TABLE VANIALA.AS_INGREDIENTS
ADD CONSTRAINT AS_INGREDIENTS_IDUNITE_FK
FOREIGN KEY (IDUNITE)
REFERENCES VANIALA.UNITE(ID);

/*

-- 1️⃣ Création de la table pour gérer plusieurs unités par médicament
CREATE TABLE MEDICAMENT_UNITE (
    ID_MEDICAMENT VARCHAR2(20) NOT NULL,
    ID_UNITE VARCHAR2(20) NOT NULL,
    QUANTITEPARPACK NUMBER DEFAULT 1,
    CONSTRAINT PK_MEDICAMENT_UNITE PRIMARY KEY (ID_MEDICAMENT, ID_UNITE),
    CONSTRAINT FK_MEDICAMENT FOREIGN KEY (ID_MEDICAMENT) REFERENCES AS_INGREDIENTS(ID),
    CONSTRAINT FK_UNITE FOREIGN KEY (ID_UNITE) REFERENCES UNITE(ID)
);

-- 2️⃣ Insertion d'exemples pour certains médicaments que nous avons déjà mis à jour
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000371', 'UNIT0002', 1);   -- Paracetamol en boîte
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000371', 'UNT003', 10);     -- Paracetamol en carton
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000371', 'UNT002', 500);    -- Paracetamol en litre (si c'était un sirop)

INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000612', 'UNT001', 20);      -- Complexe Aro Tsinay flc 20ml en gramme
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000613', 'UNT001', 20);      -- Complexe Aro Diabete 20ml en gramme

INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000738', 'UNT002', 500);     -- CDS 0.0 500ml
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000756', 'UNT002', 50);      -- SPRAY BUCCAL APHTES 50ml
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000798', 'UNT002', 30);      -- GEL PARODONTAL 30ml
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000882', 'UNT002', 300);     -- Boisson Noni 300ml

-- Ajouter des lignes pour les médicaments supplémentaires
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000355', 'UNT002', 100);  -- Argent Colloidal Btl 100ml
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000356', 'UNT002', 500);  -- Argent Colloidal Flc 500ml
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('IG000312', 'UNT002', 20);   -- 12 Sel SCHULLSER Flacon 20 ml
INSERT INTO MEDICAMENT_UNITE (ID_MEDICAMENT, ID_UNITE, QUANTITEPARPACK) VALUES ('ING00442', 'UNT001', 1);    -- ACIDE URIQUE (URICEMIE) unité par défaut



-- VANIALA.EQUIVALENCE definition

CREATE TABLE "VANIALA"."EQUIVALENCE" 
   (	"ID" VARCHAR2(100) NOT NULL ENABLE, 
	"IDPRODUIT" VARCHAR2(100), 
	"IDUNITE" VARCHAR2(100), 
	"QTE" NUMBER(10,2), 
	 CONSTRAINT "EQUIVALENCE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UNIK_PRODUIT_UNITE" UNIQUE ("IDPRODUIT", "IDUNITE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 19922944 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE UNIQUE INDEX "VANIALA"."EQUIVALENCE_PK" ON "VANIALA"."EQUIVALENCE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 
  CREATE UNIQUE INDEX "VANIALA"."UNIK_PRODUIT_UNITE" ON "VANIALA"."EQUIVALENCE" ("IDPRODUIT", "IDUNITE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;*/

-- VANIALA.EQUIVALENCE foreign keys

-- VANIALA.EQUIVALENCE foreign keys
CREATE TABLE AS_EQUIVALENCE 
(
    ID         VARCHAR2(100) NOT NULL,
    IDPRODUIT  VARCHAR2(100),
    IDUNITE    VARCHAR2(100),
    QTE        NUMBER(10,2),
    PV NUMBER(10,2)
);



ALTER TABLE AS_EQUIVALENCE 
ADD CONSTRAINT FK_AS_UNITE_EQUIVALENCE
    FOREIGN KEY (IDUNITE)
    REFERENCES AS_UNITE(ID)
    ENABLE NOVALIDATE;

CREATE OR REPLACE TRIGGER TRG_EQUI_ID
BEFORE INSERT ON AS_EQUIVALENCE
FOR EACH ROW
DECLARE
    v_num NUMBER;
BEGIN
    IF :NEW.ID IS NULL THEN
        -- Prend le prochain numéro de la séquence
        v_num := SEQ_EQUI.NEXTVAL;

        -- Construit l’ID au format QUIxxx (ex: QUI001, QUI023, QUI450)
        :NEW.ID := 'QUI' || LPAD(v_num, 3, '0');
    END IF;
END;
/


ALTER TABLE VANIALA.ETATSTOCK
MODIFY (ENTREE NUMBER(10,2), SORTIE NUMBER(10,2), RESTE NUMBER(10,2));



-- VANIALA.ETATSTOCK definition

CREATE TABLE "VANIALA"."ETATSTOCK" 
   (	"ID" VARCHAR2(255), 
	"IDPRODUIT" VARCHAR2(255), 
	"IDMAGASIN" VARCHAR2(255), 
	"IDPOINT" VARCHAR2(255), 
	"IDTYPEPRODUIT" VARCHAR2(255), 
	"IDUNITE" VARCHAR2(255), 
	"REPORT" NUMBER(*,0), 
	"ENTREE" NUMBER(*,0), 
	"SORTIE" NUMBER(*,0), 
	"RESTE" NUMBER(*,0), 
	"DATY" DATE, 
	"IDMEDICAMENT" VARCHAR2(50), 
	 CONSTRAINT "ETATSTOCK_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 186646528 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

CREATE OR REPLACE TRIGGER "VANIALA"."TRG_ETATSTOCK_ID" 
BEFORE INSERT ON ETATSTOCK
FOR EACH ROW
BEGIN
    IF :NEW.ID IS NULL THEN
        :NEW.ID := 'ETSTK' || LPAD(SEQ_ETATSTOCK.NEXTVAL, 6, '0');
    END IF;
END;
/
ALTER TRIGGER "VANIALA"."TRG_ETATSTOCK_ID" ENABLE;

CREATE UNIQUE INDEX "VANIALA"."ETATSTOCK_PK" ON "VANIALA"."ETATSTOCK" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- VANIALA.ETATSTOCK foreign keys

ALTER TABLE "VANIALA"."ETATSTOCK" ADD CONSTRAINT "ETATSTOCK_MAGASIN_FK" FOREIGN KEY ("IDMAGASIN")
	  REFERENCES "VANIALA"."MAGASIN2" ("ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "VANIALA"."ETATSTOCK" ADD CONSTRAINT "ETATSTOCK_MEDICAMENT_FK" FOREIGN KEY ("IDMEDICAMENT")
	  REFERENCES "VANIALA"."AS_INGREDIENTS" ("ID") ENABLE;
 
  ALTER TABLE "VANIALA"."ETATSTOCK" ADD CONSTRAINT "ETATSTOCK_POINT_FK" FOREIGN KEY ("IDPOINT")
	  REFERENCES "VANIALA"."POINT" ("ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "VANIALA"."ETATSTOCK" ADD CONSTRAINT "ETATSTOCK_PRODUIT_FK" FOREIGN KEY ("IDPRODUIT")
	  REFERENCES "VANIALA"."PRODUIT" ("ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "VANIALA"."ETATSTOCK" ADD CONSTRAINT "ETATSTOCK_TYPEPRODUIT_FK" FOREIGN KEY ("IDTYPEPRODUIT")
	  REFERENCES "VANIALA"."TYPE_PRODUIT" ("ID") ENABLE NOVALIDATE;
 
  ALTER TABLE "VANIALA"."ETATSTOCK" ADD CONSTRAINT "ETATSTOCK_UNITE_FK" FOREIGN KEY ("IDUNITE")
	  REFERENCES "VANIALA"."AS_UNITE" ("ID") ENABLE;


































      